name = "d1-database-cloudflare"
main = "src/index.js"
compatibility_date = "2023-08-23"


[[d1_databases]]
name = "d1-database-cloudflare-db"
binding = "DATABASE"
database_id = "dd454abd-f2cf-4a74-87e1-dc6b30e1ca77"

